name: release.yml
on:
  push: 
    branches:
      - 'release/**'
jobs:
  BUMP_VERSION:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install pysemver
        run: sudo apt-get install python3-semver
      - name: Bump version and push tag
        run: |
          tag_version=$(git -P ls-remote --tags --sort=version:refname 2> /dev/null | grep -v '\^{}' | tail -n 1 | cut -d'/' -f3)
          new_version=$(pysemver bump prerelease "${tag_version#v}")
          echo "Bump version to $new_version"